#!/bin/bash
set -e

#########################################################
#		  		VIRUS COVERAGE WRAPPER				 	#
#########################################################

# 1. Runs coverage.sh* with every sample included in samples_id.txt**
# 2. Runs graphs_coverage.R for every sample in samples_id.txt**
# * Note: This script must only be used after running wrapper_virus_mapper.sh
# ** Note: the file samples_id.txt is generated by samplesID_gen.sh

#       CONSTANTS
workingDir='/processing_Data/bioinformatics/research/20160530_METAGENOMICS_AR_IC_T/'
virDB="${workingDir}REFERENCES/VIRUS_GENOME_REFERENCE/"

# Calculates coverage for each sample
cat ${workingDir}ANALYSIS/samples_id.txt | while read in
do
	sampleDir="${workingDir}ANALYSIS/06-virus/${in}/"
	${workingDir}ANALYSIS/SRC/coverage.sh $sampleDir $virDB
done

# generates coverage data for each sample
cat ${workingDir}ANALYSIS/samples_id.txt | while read in
do
	Rscript ${workingDir}ANALYSIS/SRC/graphs_coverage.R "${workingDir}ANALYSIS/06-virus/${in}/coverage/" ${in}
done
