#!/bin/bash
set -e
#########################################################
#		  		BACTERIA BLAST WRAPPER				 	#
#########################################################

# 1. Runs blast.sh* with every sample included in samples_id.txt**
# * Note: This script must only be used after running wrapper_bacteria_assembly.sh
# ** Note: the file samples_id.txt is generated by samplesID_gen.sh

#       CONSTANTS
workingDir='/processing_Data/bioinformatics/research/20160530_METAGENOMICS_AR_IC_T/'
bacDB="${workingDir}REFERENCES/BACTERIA_GENOME_REFERENCE/"

source ${workingDir}ANALYSIS/SRC/blast.sh
cat ${workingDir}ANALYSIS/samples_id.txt | while read in
do
	sampleDir="${workingDir}ANALYSIS/05-bacteria/${in}/"
	blast $sampleDir $bacDB
done

