#!/bin/bash
set -e

#########################################################
#		  		FUNGI ASSEMBLY WRAPPER				 	#
#########################################################

# 1. Runs assembly.sh* with every sample included in samples_id.txt**
# * Note: This script must only be used after running wrapper_fungi_mapper.sh
# ** Note: the file samples_id.txt is generated by samplesID_gen.sh

#       CONSTANTS
workingDir='/processing_Data/bioinformatics/research/20160530_METAGENOMICS_AR_IC_T/'

source ${workingDir}ANALYSIS/SRC/assembly.sh
cat ${workingDir}/ANALYSIS/samples_id.txt | while read in
do
	mappedDir="${workingDir}ANALYSIS/07-fungi/${in}/reads/"
	assemble $mappedDir
done
