#!/bin/bash
set -e

#########################################################
#		  		PARSITE MAPPER WRAPPER				 	#
#########################################################

# 1. Runs preprocessing.sh with every sample included in samples_id.txt*
# 2. Runs perl script to generate fastqc unified report
# * Note: the file samples_id.txt is generated by samplesID_gen.sh


#       CONSTANTS	
workingDir='/processing_Data/bioinformatics/research/20160530_METAGENOMICS_AR_IC_T/'

cat ${workingDir}ANALYSIS/samples_id.txt | while read in
do 
	bash ${workingDir}ANALYSIS/SRC/preprocessing.sh -s $in
done

# generate fastqc report: 
perl ${workingDir}ANALYSIS/SRC/html/fastqc/listFastQCReports.pl ${workingDir}ANALYSIS/99-stats/ > ${workingDir}ANALYSIS/99-stats/table.html
perl ${workingDir}ANALYSIS/SRC/html/fastqc/createHTML.pl

