#!/bin/bash
set -e

#########################################################
#		  		HOST REMOVAL WRAPPER				 	#
#########################################################

# 1. Runs host.sh* with every sample included in samples_id.txt**
# * Note: This script must only be used after running wrapper_preprocessing.sh
# ** Note: the file samples_id.txt is generated by samplesID_gen.sh

#	CONSTANTS
workingDir="/processing_Data/bioinformatics/research/20160530_METAGENOMICS_AR_IC_T/"

cat ${workingDir}ANALYSIS/samples_id.txt | while read in
do
    bash ${workingDir}ANALYSIS/SRC/host.sh -s $in
done

